version: 1.1.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: AcadLib/AcadLib.csproj
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 3dkguU1xfhgsgGezjNpbdWGMiFrlqPCi/ZhTCt5MCmSJ6cS3sXtQqTU+t86tErvN
  on:
    branch: master  